from pathlib import Path

ROOT = Path(__file__).resolve().parent
app_path = ROOT / 'app.py'
app = app_path.read_text(encoding='utf-8')

needle = '_load_local_env()\nimport json\n'
insert = '''_load_local_env()\n\n# Always resolve the database from the application directory (or an explicit\n# DATABASE_PATH). This prevents deployment failures when the process working\n# directory differs from the project root.\nDATABASE_PATH = os.path.abspath(os.environ.get(\n    "DATABASE_PATH",\n    os.path.join(os.path.dirname(os.path.abspath(__file__)), "orders.db")\n))\nimport json\n'''
assert needle in app
app = app.replace(needle, insert, 1)
app = app.replace('MAX_CONTENT_LENGTH=8 * 1024 * 1024', 'MAX_CONTENT_LENGTH=32 * 1024 * 1024', 1)
app = app.replace('    "delivery": (60, 20),\n}', '    "delivery": (60, 20),\n    "chat": (60, 40),\n}', 1)
assert app.count('sqlite3.connect("orders.db")') >= 100
app = app.replace('sqlite3.connect("orders.db")', 'sqlite3.connect(DATABASE_PATH)')
old = '''    if _ENVIRONMENT == "production" and request.is_secure:\n        response.headers.setdefault("Strict-Transport-Security", "max-age=31536000; includeSubDomains")\n\n    # Inject the CSRF token into existing POST forms so legacy templates do not\n'''
new = '''    if _ENVIRONMENT == "production" and request.is_secure:\n        response.headers.setdefault("Strict-Transport-Security", "max-age=31536000; includeSubDomains")\n\n    # Never let shared/browser caches retain authenticated pages or private\n    # account/order information. Public catalog pages remain cacheable.\n    if session.get("customer_id") or session.get("admin_logged_in") or session.get("supplier_logged_in"):\n        response.headers.setdefault("Cache-Control", "private, no-store")\n\n    # Inject the CSRF token into existing POST forms so legacy templates do not\n'''
assert old in app
app = app.replace(old, new, 1)
old = '''SUPPLIER_USERNAME = (\n    os.getenv("SUPPLIER_USERNAME", "").strip()\n    or os.getenv("SUPPLIER_EMAIL", "").strip()\n    or "admin"\n)\nSUPPLIER_PASSWORD = os.getenv("SUPPLIER_PASSWORD", "") or "admin"\n'''
new = '''SUPPLIER_USERNAME = (\n    os.getenv("SUPPLIER_USERNAME", "").strip()\n    or os.getenv("SUPPLIER_EMAIL", "").strip()\n)\nSUPPLIER_PASSWORD = os.getenv("SUPPLIER_PASSWORD", "")\n'''
assert old in app
app = app.replace(old, new, 1)
old = '''@app.route("/api/chat/conversations", methods=["GET","POST"])\ndef chat_conversations_api():\n    ensure_live_chat_tables()\n'''
new = '''@app.route("/api/chat/conversations", methods=["GET","POST"])\ndef chat_conversations_api():\n    if _api_rate_limited("chat"):\n        return jsonify({"success": False, "error": "Too many chat requests. Please wait a moment."}), 429\n    ensure_live_chat_tables()\n'''
assert old in app
app = app.replace(old, new, 1)
start = app.index('@app.route("/api/chat/messages")')
end = app.index('@app.route("/api/chat/send", methods=["POST"])', start)
chat_route = '''@app.route("/api/chat/messages")\ndef chat_messages_api():\n    if _api_rate_limited("chat"):\n        return jsonify({"success": False, "error": "Too many chat requests. Please wait a moment."}), 429\n    ensure_live_chat_tables()\n    is_admin=bool(session.get("admin_logged_in"))\n    conv_id=request.args.get("conversation_id", type=int)\n    requested_customer=request.args.get("customer_id", type=int)\n    if not is_admin and not session.get("customer_id"):\n        return jsonify({"success":False,"error":"Login required"}),401\n    conn=sqlite3.connect(DATABASE_PATH); conn.row_factory=sqlite3.Row; cur=conn.cursor()\n    try:\n        if conv_id:\n            cur.execute("SELECT * FROM chat_conversations WHERE id=?",(conv_id,)); conv=cur.fetchone()\n            if not conv: return jsonify({"success":False,"error":"Conversation not found"}),404\n            if not is_admin and conv['customer_id'] != session.get('customer_id'):\n                return jsonify({"success":False,"error":"Forbidden"}),403\n        else:\n            cid=requested_customer if is_admin and requested_customer else session.get('customer_id')\n            if not cid: return jsonify({"success":False,"error":"Conversation required"}),400\n            cur.execute("SELECT * FROM chat_conversations WHERE customer_id=? ORDER BY updated_at DESC LIMIT 1",(cid,)); conv=cur.fetchone()\n            if not conv: return jsonify({"success":True,"conversation":None,"messages":[],"unread_total":0})\n            conv_id=conv['id']\n        after=max(0, request.args.get("after_id",0,type=int) or 0)\n        cur.execute("SELECT id,conversation_id,customer_id,order_id,sender_type,message,is_read,created_at FROM chat_messages WHERE conversation_id=? AND id>? ORDER BY id ASC LIMIT 100",(conv_id,after))\n        messages=[dict(r) for r in cur.fetchall()]\n        recipient='customer' if is_admin else 'admin'\n        cur.execute("UPDATE chat_messages SET is_read=1 WHERE conversation_id=? AND sender_type=? AND is_read=0",(conv_id,recipient))\n        conn.commit()\n        cur.execute("SELECT COUNT(*) FROM chat_messages WHERE sender_type=? AND is_read=0" , ('customer' if is_admin else 'admin',))\n        unread_total=cur.fetchone()[0]\n        cur.execute("SELECT c.*,cu.name customer_name,cu.email customer_email FROM chat_conversations c JOIN customers cu ON cu.id=c.customer_id WHERE c.id=?",(conv_id,)); conv_row=cur.fetchone()\n        if not conv_row: return jsonify({"success":False,"error":"Conversation no longer exists"}),404\n        conv=dict(conv_row)\n        return jsonify({"success":True,"conversation":conv,"messages":messages,"unread_total":unread_total})\n    except Exception as exc:\n        security_log("chat_messages_error", repr(exc)[:1000])\n        return jsonify({"success":False,"error":"Chat is temporarily unavailable. Please refresh and try again."}),503\n    finally:\n        conn.close()\n\n'''
app = app[:start] + chat_route + app[end:]
old = '''def chat_send_api():\n    """Send a customer/admin chat message without letting notification failures block delivery."""\n    ensure_live_chat_tables()\n'''
new = '''def chat_send_api():\n    """Send a customer/admin chat message without letting notification failures block delivery."""\n    if _api_rate_limited("chat"):\n        return jsonify({"success": False, "error": "Too many chat requests. Please wait a moment."}), 429\n    ensure_live_chat_tables()\n'''
assert old in app
app = app.replace(old, new, 1)
old = '''@app.route("/supplier/login", methods=["GET", "POST"])\n@app.route("/supplier-login", methods=["GET", "POST"])\ndef supplier_login():\n    if request.method == "POST":\n'''
new = '''@app.route("/supplier/login", methods=["GET", "POST"])\n@app.route("/supplier-login", methods=["GET", "POST"])\ndef supplier_login():\n    if not SUPPLIER_USERNAME or not SUPPLIER_PASSWORD:\n        return render_template("supplier_login.html", error="Supplier access is not enabled on this deployment."), 503\n    if request.method == "POST":\n'''
assert old in app
app = app.replace(old, new, 1)
old = '''@app.route("/supplier")\n@app.route("/supplier-dashboard")\ndef supplier_dashboard():\n    if not session.get("supplier_logged_in"):\n'''
new = '''@app.route("/supplier")\n@app.route("/supplier-dashboard")\ndef supplier_dashboard():\n    if not SUPPLIER_USERNAME or not SUPPLIER_PASSWORD:\n        return "Supplier portal is not enabled.", 404\n    if not session.get("supplier_logged_in"):\n'''
assert old in app
app = app.replace(old, new, 1)
app = app.replace('if len(new_password) < 6:', 'if len(new_password) < 8:', 1)
app = app.replace('error="New password must be at least 6 characters."', 'error="New password must be at least 8 characters."', 1)
app = app.replace('if len(password) < 6:', 'if len(password) < 8:', 1)
app = app.replace('error="Password must be at least 6 characters."', 'error="Password must be at least 8 characters."', 1)
app_path.write_text(app, encoding='utf-8')

(ROOT / 'Procfile').write_text('web: gunicorn --workers 2 --threads 4 --timeout 120 --access-logfile - --error-logfile - wsgi:app\n', encoding='utf-8')
(ROOT / 'SECURITY_DEPLOYMENT.md').write_text('''# CopierStore — production security & deployment\n\nThis package is prepared as a deployment baseline. It contains no customer accounts, orders, receipts, repair uploads, chat history, admin password hash, Git history, or backup databases.\n\n## Required before going live\n\n1. Set a unique `SECRET_KEY` (32+ random characters; 64+ is recommended).\n2. Set a strong `ADMIN_USERNAME`, `ADMIN_PASSWORD`, and `ADMIN_RECOVERY_KEY` in the hosting provider's secret/environment settings.\n3. Configure Turso with `TURSO_DATABASE_URL` and `TURSO_AUTH_TOKEN` for persistent production data. Do not rely on the local SQLite file for a public Render service unless persistent disk storage is explicitly configured.\n4. Configure real store/payment settings in the admin dashboard.\n5. Configure Gemini/Lalamove only when the corresponding features are needed.\n6. Enable HTTPS and keep `SESSION_COOKIE_SECURE=1`.\n\n## Security controls included\n\n- HttpOnly + SameSite session cookies\n- Secure cookies in production\n- CSRF tokens for browser form POSTs\n- Same-origin checks for JSON APIs\n- Security headers including HSTS in HTTPS production\n- No-store caching for authenticated responses\n- Login/password-reset throttling\n- API rate limiting, including chat polling/sending\n- Password hashing with Werkzeug\n- Server-side price/stock validation\n- Safe local redirect validation\n- Upload extension + file-signature validation\n- Private payment/repair files outside `static/`\n- Ownership checks for customer orders, chats, repairs and private files\n- Stable numeric product URLs with legacy product-name URL compatibility\n- Bounded chat polling payloads\n- Production WSGI server configuration\n- `/health` endpoint for hosting health checks\n\n## Important limitation\n\nNo application can honestly be called "perfect" or "100% secure". Security also depends on Render/Turso configuration, secret rotation, DNS/HTTPS, database permissions, operating-system patching, payment-provider settings, and the code added after this package is deployed. Treat this package as a hardened deployment baseline and run a real HTTPS/browser smoke test after deployment.\n''', encoding='utf-8')
(ROOT / 'render.yaml').write_text('''services:\n  - type: web\n    name: copierstore\n    runtime: python\n    buildCommand: pip install -r requirements.txt\n    startCommand: gunicorn --workers 2 --threads 4 --timeout 120 --access-logfile - --error-logfile - wsgi:app\n    healthCheckPath: /health\n    autoDeploy: true\n    envVars:\n      - key: FLASK_ENV\n        value: production\n      - key: FLASK_DEBUG\n        value: "0"\n      - key: SESSION_COOKIE_SECURE\n        value: "1"\n      - key: SECRET_KEY\n        sync: false\n      - key: ADMIN_USERNAME\n        sync: false\n      - key: ADMIN_PASSWORD\n        sync: false\n      - key: ADMIN_RECOVERY_KEY\n        sync: false\n      - key: GEMINI_API_KEY\n        sync: false\n      - key: LALAMOVE_API_KEY\n        sync: false\n      - key: LALAMOVE_API_SECRET\n        sync: false\n      - key: LALAMOVE_ENV\n        value: production\n      - key: LALAMOVE_MARKET\n        value: PH\n      - key: LALAMOVE_SERVICE_TYPE\n        value: MOTORCYCLE\n      - key: TURSO_DATABASE_URL\n        sync: false\n      - key: TURSO_AUTH_TOKEN\n        sync: false\n      - key: SUPPLIER_USERNAME\n        sync: false\n      - key: SUPPLIER_PASSWORD\n        sync: false\n''', encoding='utf-8')
